version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./your_private.key:/etc/nginx/certs/your_private.key
      - ./your_certificate.crt:/etc/nginx/certs/your_certificate.crt
